services:
  mysql-gyms:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=rootpass'
      - 'MYSQL_USER=user'
    ports:
      - '3306'
    networks:
      - mynetwork

  spring-app:
    build: .
    depends_on:
      - mysql-gyms
    networks:
      - mynetwork
    expose:
      - "9090"

networks:
  mynetwork:
    driver: bridge
