services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-gymmanagement
    ports:
      - 8080:8080
    restart: unless-stopped
    image: miguelcruzeiro/fitmonitor_gymmanagement:v4
    expose:
      - 8080
    environment:
      COGNITO_JWKS_URL: ${COGNITO_JWKS_URL}
      EXTERNAL_AUTH_TOKEN_URL: ${EXTERNAL_AUTH_TOKEN_URL}
      EXTERNAL_AUTH_CLIENT_CREDENTIALS: ${EXTERNAL_AUTH_CLIENT_CREDENTIALS}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - default

networks:
  default:
    driver: bridge
